# Generated by Django 4.2.6 on 2023-11-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classwise_Fee',
            fields=[
                ('student_class', models.CharField(choices=[('nursery', 'Nursery'), ('pp-I', 'PP-I'), ('pp-II', 'PP-II'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=10, primary_key=True, serialize=False)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('exam_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cocurriculars',
            fields=[
                ('activity_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50)),
                ('trainer', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('work_type', models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non Teaching')], max_length=15)),
                ('working_hours', models.CharField(default='0', max_length=20)),
                ('subject_id', models.CharField(default='0', max_length=10)),
                ('subject', models.CharField(default='0', max_length=100)),
                ('role', models.CharField(default='teacher', max_length=100)),
                ('account_no', models.BigIntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('adm_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('student_class', models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('pp-I', 'PP-I'), ('pp-II', 'PP-II'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=10, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('area_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('area_name', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('adm_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.student')),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exam_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('miscellaneous_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_fee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fee_concession', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.transportation')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classwise_fee')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=10, null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_class', models.CharField(blank=True, max_length=30, null=True)),
                ('section', models.CharField(default='A', max_length=30)),
                ('first_language', models.DecimalField(decimal_places=2, max_digits=5)),
                ('second_language', models.DecimalField(decimal_places=2, max_digits=5)),
                ('third_language', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mathematics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('science', models.DecimalField(decimal_places=2, max_digits=5)),
                ('social', models.DecimalField(decimal_places=2, max_digits=5)),
                ('computers', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overall_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adm_no', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Cocurricular_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_class', models.CharField(blank=True, max_length=30, null=True)),
                ('section', models.CharField(blank=True, max_length=30, null=True)),
                ('activity_name', models.CharField(max_length=50)),
                ('performance_remark', models.CharField(max_length=200)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cocurriculars')),
                ('adm_no', models.ForeignKey(default='1234', on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('receipt_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adm_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.feedetails')),
            ],
        ),
    ]
