# Generated by Django 4.2.6 on 2023-11-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicgrades',
            name='adm_no',
            field=models.ForeignKey(default='1234', on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
