# Generated by Django 4.2.6 on 2023-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_classwise_fee_transportation_feedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('work_type', models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non Teaching')], max_length=15)),
                ('working_hours', models.IntegerField()),
                ('subject_id', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.BigIntegerField()),
                ('bank', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
