# Generated by Django 4.2.6 on 2023-10-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_academicgrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='area_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
