# Generated by Django 4.2.6 on 2023-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transportation_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetails',
            name='transport_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
