# Generated by Django 4.2.6 on 2023-10-31 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_feedetails_transport_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('purpose', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('receipt_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('student_name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adm_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
