# Generated by Django 4.2.6 on 2023-10-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_expenditurerecord_feerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='adm_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.feedetails'),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='section',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='student_class',
            field=models.CharField(max_length=30),
        ),
    ]
