# Generated by Django 4.2.6 on 2023-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_feerecord_adm_no_alter_feerecord_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocurriculars',
            fields=[
                ('activity_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='expenditurerecord',
            name='date',
            field=models.DateField(),
        ),
    ]
