# Generated by Django 4.2.6 on 2023-11-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cocurriculars_alter_expenditurerecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocurriculars',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cocurriculars',
            name='trainer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Cocurricular_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('performance_remark', models.CharField(max_length=200)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cocurriculars')),
            ],
        ),
    ]
