# Generated by Django 4.2.6 on 2023-11-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cocurriculars_description_cocurriculars_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocurricular_performance',
            name='adm_no',
            field=models.ForeignKey(default='1234', on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
        migrations.AddField(
            model_name='cocurricular_performance',
            name='section',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cocurricular_performance',
            name='student_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cocurricular_performance',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
