# Generated by Django 4.2.6 on 2023-11-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cocurricular_performance_adm_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='teacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subject',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subject_id',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
