# Generated by Django 4.2.6 on 2023-11-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_employee_role_alter_employee_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_hours',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
