# Generated by Django 4.2.6 on 2023-11-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_employee_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicgrades',
            name='section',
            field=models.CharField(default='A', max_length=30),
        ),
        migrations.AddField(
            model_name='academicgrades',
            name='student_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='academicgrades',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicgrades',
            name='academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
